import { useRef, useLayoutEffect, useState } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useSimulation } from '@/context/SimulationContext';
import { AI_AGENTS, generateMockAnalysis, calculateConsensus } from '@/lib/ai-agents';
import { FileText, Download, Share2, CheckCircle, AlertTriangle, TrendingUp, DollarSign, Heart, Shield } from 'lucide-react';

gsap.registerPlugin(ScrollTrigger);

export function ComprehensiveResults() {
  const sectionRef = useRef<HTMLElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const { decision, factors, simulationResult } = useSimulation();
  
  const [isGenerating, setIsGenerating] = useState(false);
  const [showReport, setShowReport] = useState(false);

  // Generate analyses for report
  const analyses = AI_AGENTS.map(agent => generateMockAnalysis(agent.id, decision, factors));
  const { consensus, divergentPoints, overallConfidence } = calculateConsensus(analyses);

  useLayoutEffect(() => {
    const section = sectionRef.current;
    const content = contentRef.current;
    if (!section || !content) return;

    const ctx = gsap.context(() => {
      gsap.fromTo(
        content,
        { y: 50, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 0.8,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: section,
            start: 'top 80%',
            end: 'top 50%',
            scrub: 1,
          },
        }
      );
    }, section);

    return () => ctx.revert();
  }, []);

  const handleGenerateReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
      setShowReport(true);
    }, 1500);
  };

  const handleExportPDF = () => {
    // In a real implementation, this would generate a PDF
    // For now, we'll create a text report
    const report = generateTextReport();
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `foresight-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateTextReport = () => {
    return `
FORESIGHT DECISION ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}

===================================
YOUR DECISION
===================================
${decision || 'No decision entered'}

===================================
YOUR PROFILE
===================================
Risk Tolerance: ${factors.riskTolerance}%
Financial Stability: ${factors.financialStability}%
Discipline Level: ${factors.disciplineLevel}%
Support System: ${factors.supportSystem}%

===================================
CONSENSUS
===================================
${consensus}
Overall Confidence: ${overallConfidence}%

===================================
AI ADVISOR ANALYSES
===================================

${analyses.map(a => `
--- ${a.agentName} ---
Perspective: ${a.perspective}
Recommendation: ${a.recommendation}
Confidence: ${a.confidence}%

Key Insights:
${a.keyInsights.map(i => `- ${i}`).join('\n')}

Risks:
${a.risks.map(r => `- ${r}`).join('\n')}

Opportunities:
${a.opportunities.map(o => `- ${o}`).join('\n')}

Action Items:
${a.actionItems.map((item, i) => `${i + 1}. ${item}`).join('\n')}
`).join('\n')}

===================================
SIMULATION RESULTS
===================================

3 Months:
${simulationResult ? JSON.stringify(simulationResult.threeMonths, null, 2) : 'Not calculated'}

1 Year:
${simulationResult ? JSON.stringify(simulationResult.oneYear, null, 2) : 'Not calculated'}

5 Years:
${simulationResult ? JSON.stringify(simulationResult.fiveYears, null, 2) : 'Not calculated'}

Summary: ${simulationResult?.summary || 'Not available'}
Alternative Path: ${simulationResult?.alternativePath || 'Not available'}

===================================
Report generated by Foresight AI
`;
  };

  const getAgentIcon = (agentId: string) => {
    switch (agentId) {
      case 'risk-analyst': return <Shield className="w-5 h-5" />;
      case 'opportunity-coach': return <TrendingUp className="w-5 h-5" />;
      case 'financial-advisor': return <DollarSign className="w-5 h-5" />;
      case 'life-mentor': return <Heart className="w-5 h-5" />;
      default: return <CheckCircle className="w-5 h-5" />;
    }
  };

  return (
    <section
      ref={sectionRef}
      data-section="comprehensive-results"
      className="relative w-full py-16 lg:py-24"
    >
      <div ref={contentRef} className="max-w-6xl mx-auto px-6">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex items-center justify-center gap-2 mb-4">
            <FileText className="w-5 h-5 text-foresight-accent" />
            <span className="micro-label">COMPREHENSIVE REPORT</span>
          </div>
          <h2 className="font-display text-4xl lg:text-5xl font-light text-foresight-text mb-4">
            Your Decision Report
          </h2>
          <p className="text-lg text-foresight-text-muted max-w-2xl mx-auto">
            Generate a comprehensive report with insights from all AI advisors, 
            simulation results, and actionable recommendations.
          </p>
        </div>

        {!showReport ? (
          // Generate Report View
          <div className="max-w-2xl mx-auto">
            <div className="glass-card-strong p-8 text-center">
              <div className="w-20 h-20 rounded-full bg-foresight-accent/20 flex items-center justify-center mx-auto mb-6">
                <FileText className="w-10 h-10 text-foresight-accent" />
              </div>
              
              <h3 className="font-display text-2xl text-foresight-text mb-4">
                Ready to Generate Your Report?
              </h3>
              
              <p className="text-foresight-text-muted mb-8">
                Your report will include:
              </p>
              
              <div className="grid grid-cols-2 gap-4 mb-8 text-left">
                <div className="flex items-center gap-3 p-3 glass-card">
                  <CheckCircle className="w-5 h-5 text-emerald-400" />
                  <span className="text-sm text-foresight-text">AI Advisor Analyses</span>
                </div>
                <div className="flex items-center gap-3 p-3 glass-card">
                  <CheckCircle className="w-5 h-5 text-emerald-400" />
                  <span className="text-sm text-foresight-text">Consensus & Confidence</span>
                </div>
                <div className="flex items-center gap-3 p-3 glass-card">
                  <CheckCircle className="w-5 h-5 text-emerald-400" />
                  <span className="text-sm text-foresight-text">Timeline Simulations</span>
                </div>
                <div className="flex items-center gap-3 p-3 glass-card">
                  <CheckCircle className="w-5 h-5 text-emerald-400" />
                  <span className="text-sm text-foresight-text">Action Plan & Resources</span>
                </div>
              </div>
              
              <button
                onClick={handleGenerateReport}
                disabled={isGenerating}
                className="btn-primary flex items-center justify-center gap-2 mx-auto px-8 py-4 disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <div className="w-5 h-5 border-2 border-foresight-accent/30 border-t-foresight-accent rounded-full animate-spin" />
                    <span>Generating Report...</span>
                  </>
                ) : (
                  <>
                    <FileText className="w-5 h-5" />
                    <span>Generate Report</span>
                  </>
                )}
              </button>
            </div>
          </div>
        ) : (
          // Report View
          <div className="space-y-6">
            {/* Report Header */}
            <div className="glass-card-strong p-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
              <div>
                <h3 className="font-display text-xl text-foresight-text mb-1">
                  Decision Analysis Report
                </h3>
                <p className="text-sm text-foresight-text-muted">
                  Generated on {new Date().toLocaleDateString()}
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={handleExportPDF}
                  className="btn-secondary flex items-center gap-2 px-4 py-2 text-sm"
                >
                  <Download className="w-4 h-4" />
                  <span>Export</span>
                </button>
                <button
                  onClick={() => setShowReport(false)}
                  className="btn-primary flex items-center gap-2 px-4 py-2 text-sm"
                >
                  <Share2 className="w-4 h-4" />
                  <span>New Report</span>
                </button>
              </div>
            </div>

            {/* Decision Summary */}
            <div className="glass-card p-6">
              <h4 className="font-display text-lg text-foresight-text mb-3">Your Decision</h4>
              <p className="text-foresight-text-muted leading-relaxed">
                {decision || 'No decision entered'}
              </p>
            </div>

            {/* Consensus */}
            <div className="glass-card-strong p-6">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-xl bg-foresight-accent/20 flex items-center justify-center flex-shrink-0">
                  <CheckCircle className="w-6 h-6 text-foresight-accent" />
                </div>
                <div className="flex-1">
                  <h4 className="font-display text-lg text-foresight-text mb-2">Consensus</h4>
                  <p className="text-foresight-text-muted leading-relaxed mb-4">{consensus}</p>
                  <div className="flex items-center gap-3">
                    <span className="text-sm text-foresight-text-muted">Overall Confidence:</span>
                    <div className="flex items-center gap-2">
                      <div className="w-32 h-2 bg-white/10 rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-foresight-accent transition-all duration-500"
                          style={{ width: `${overallConfidence}%` }}
                        />
                      </div>
                      <span className="text-foresight-accent font-medium">{overallConfidence}%</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Divergent Points */}
            {divergentPoints.length > 0 && (
              <div className="glass-card p-6 border-l-4 border-yellow-500">
                <div className="flex items-start gap-3">
                  <AlertTriangle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <h4 className="font-medium text-foresight-text mb-2">Points of Divergence</h4>
                    <ul className="space-y-2">
                      {divergentPoints.map((point, idx) => (
                        <li key={idx} className="text-sm text-foresight-text-muted">{point}</li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            )}

            {/* Agent Analyses */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {analyses.map((analysis) => {
                const agent = AI_AGENTS.find(a => a.id === analysis.agentId);
                return (
                  <div key={analysis.agentId} className="glass-card p-6">
                    <div className="flex items-center gap-3 mb-4">
                      <div 
                        className="w-10 h-10 rounded-xl flex items-center justify-center text-white"
                        style={{ background: agent?.color }}
                      >
                        {getAgentIcon(analysis.agentId)}
                      </div>
                      <div>
                        <h4 className="font-display text-lg text-foresight-text">{agent?.name}</h4>
                        <p className="text-xs text-foresight-text-muted">{agent?.role}</p>
                      </div>
                      <span 
                        className="ml-auto text-sm font-medium px-3 py-1 rounded-full"
                        style={{ 
                          background: `${agent?.color}20`,
                          color: agent?.color 
                        }}
                      >
                        {analysis.confidence}%
                      </span>
                    </div>
                    
                    <p className="text-sm text-foresight-text-muted mb-4">{analysis.perspective}</p>
                    <p className="text-sm text-foresight-text mb-4">{analysis.recommendation}</p>
                    
                    <div className="space-y-3">
                      {analysis.keyInsights.length > 0 && (
                        <div>
                          <h5 className="text-xs font-medium text-foresight-text-muted mb-2">Key Insights</h5>
                          <ul className="space-y-1">
                            {analysis.keyInsights.slice(0, 2).map((insight, idx) => (
                              <li key={idx} className="text-xs text-foresight-text-muted flex items-start gap-2">
                                <span style={{ color: agent?.color }}>•</span>
                                {insight}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Simulation Results */}
            {simulationResult && (
              <div className="glass-card p-6">
                <h4 className="font-display text-lg text-foresight-text mb-4">Timeline Projections</h4>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div className="glass-card p-4 text-center">
                    <p className="text-xs text-foresight-text-muted mb-1">3 Months</p>
                    <p className="text-2xl font-display text-foresight-text">
                      {Math.round((simulationResult.threeMonths.financial.value + simulationResult.threeMonths.emotional.value) / 2)}%
                    </p>
                    <p className="text-xs text-foresight-text-muted">Success Score</p>
                  </div>
                  <div className="glass-card p-4 text-center">
                    <p className="text-xs text-foresight-text-muted mb-1">1 Year</p>
                    <p className="text-2xl font-display text-foresight-text">
                      {Math.round((simulationResult.oneYear.financial.value + simulationResult.oneYear.emotional.value) / 2)}%
                    </p>
                    <p className="text-xs text-foresight-text-muted">Success Score</p>
                  </div>
                  <div className="glass-card p-4 text-center">
                    <p className="text-xs text-foresight-text-muted mb-1">5 Years</p>
                    <p className="text-2xl font-display text-foresight-text">
                      {Math.round((simulationResult.fiveYears.financial.value + simulationResult.fiveYears.emotional.value) / 2)}%
                    </p>
                    <p className="text-xs text-foresight-text-muted">Success Score</p>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </section>
  );
}
